### PR TITLE
Update action.php

### PR DESCRIPTION
**Pull request by chtiland**
Added **.svg** extension to make it compatible with last version of Dokuwiki (Igor)

### CODE REVIEW

**Comment by haobug** [comment]
@chtiland hi i have no php env at hand. 
is it support more extensions of the interwiki logo/icons image file?

**Comment by haobug** [comment]
and nice header picture.

**Comment by haobug** [comment]
thanks for you help @chtiland 

i warried about if it breaks the toolbar launch icon at that time,it has been mis-located before.

i have confirm in from online code editor. you change looks okay.

**Comment by ParoTheParrot** [comment]
@haobug , @chtiland !
Is interwiki compatible to Igor with this modifications?
In this case, please update https://www.dokuwiki.org/plugin:interwiki.
TIA, Paro!

**Pull request merged**
